[project]
name = "geometryawaremcts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cloudpickle>=3.1.2",
    "matplotlib>=3.10.8",
    "numba>=0.64.0",
    "numpy>=2.4.3",
    "pandas>=3.0.1",
    "pillow>=12.1.1",
    "psutil>=7.2.2",
    "pydantic>=2.12.5",
    "pyvis>=0.3.2",
    "pyyaml>=6.0.3",
    "sympy>=1.14.0",
    "tqdm>=4.67.3",
]
